import pandas as pd
import os
import re
import logging
import json
from typing import Dict, List, Any, Optional, Tuple, Union
from sklearn.preprocessing import LabelEncoder

# Centralized Logger Configuration
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

REPLACE_NAN = 'NAN'
_OUTPUT_CLEARED = False


def get_config_path() -> str:
    """Gets the absolute path to the config.json file.

    Returns:
        str: Absolute path to config.json.
    """
    return os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'config.json')


def load_config() -> Dict[str, Any]:
    """Loads configuration from config.json.

    Returns:
        Dict[str, Any]: Configuration dictionary.
    """
    cfg_path = get_config_path()
    if os.path.exists(cfg_path):
        try:
            with open(cfg_path) as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError) as e:
            logger.error(f"Failed to load config from {cfg_path}: {e}")
    return {}


def get_output_path() -> str:
    """Retrieves the output directory path from config or defaults to './output/'.
    Ensures the directory exists and is cleared once per session.

    Returns:
        str: Path to the output directory.
    """
    global _OUTPUT_CLEARED
    cfg = load_config()
    path = cfg.get('app', {}).get('output_path', './output/')
    create_new_directory(path, force_clear=not _OUTPUT_CLEARED)
    _OUTPUT_CLEARED = True
    return path


def create_new_directory(dir_path: str, force_clear: bool = True) -> None:
    """Creates a directory if it doesn't exist. Optionally clears its contents.

    Args:
        dir_path: Path to the directory.
        force_clear: Whether to delete all files in the directory if it exists.
    """
    if not os.path.exists(dir_path):
        os.makedirs(dir_path)
        logger.info(f"Directory '{dir_path}' created.")
    elif force_clear:
        for f in os.listdir(dir_path):
            file_path = os.path.join(dir_path, f)
            try:
                if os.path.isfile(file_path):
                    os.remove(file_path)
            except Exception as e:
                logger.warning(f"Failed to remove {file_path}: {e}")


def convert_categorical_columns(data: pd.DataFrame) -> Tuple[pd.DataFrame, Dict[str, Dict[int, str]]]:
    """Converts object-type columns in a DataFrame to numerical labels.

    Args:
        data: The input DataFrame.

    Returns:
        Tuple[pd.DataFrame, Dict[str, Dict[int, str]]]: 
            - The transformed DataFrame.
            - A mapping of numerical labels to original category names for each column.
    """
    df = data.copy()
    label_mappings = {}
    label_encoder = LabelEncoder()
    for column in df.columns:
        if df[column].dtype == 'object':
            df[column] = label_encoder.fit_transform(df[column].astype(str))
            label_mappings[column] = dict(zip(
                range(len(label_encoder.classes_)),
                label_encoder.classes_
            ))
    return df, label_mappings


def get_back_original_label_from_numerical_label(
    label_mappings: Dict[str, Dict[int, str]], 
    column_name: str, 
    numerical_label: Union[int, float, str]
) -> Optional[str]:
    """Retrieves the original category label from a numerical label using provided mappings.

    Args:
        label_mappings: Mappings generated by convert_categorical_columns.
        column_name: The name of the column.
        numerical_label: The numerical label to look up.

    Returns:
        Optional[str]: The original label, or None if not found.
    """
    try:
        idx = int(float(numerical_label))
        return label_mappings.get(column_name, {}).get(idx)
    except (ValueError, TypeError):
        return None


def format_name(name: Any) -> str:
    """Formats a string by stripping, replacing spaces with underscores, and removing parentheses.

    Args:
        name: The object to format.

    Returns:
        str: The formatted string.
    """
    name_str = str(name).strip()
    return name_str.replace(" ", "_").replace("(", "").replace(")", "")


def normalize_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Normalizes a DataFrame for survey analysis by cleaning strings and converting indices.

    Args:
        df: Input DataFrame.

    Returns:
        pd.DataFrame: Normalized DataFrame.
    """
    columns_to_keep = [
        'Variable', 'number_questions', 'column_index_from', 'Related_Variables',
        'number_options', 'column_index', 'used_as_moderator', 'Relation_Type',
        'parameter', 'high_threshold', 'moderate_threshold', 'Variable_1', 'Variable_2'
    ]

    # Filter columns that actually exist
    df = df[[col for col in columns_to_keep if col in df.columns]].copy()

    # Handle missing values
    df = df.fillna(REPLACE_NAN).replace('', REPLACE_NAN)

    # String normalization logic
    def normalize_string(x: Any) -> str:
        if not isinstance(x, str):
            x = str(x)
        x = x.strip()
        x = re.sub(r'\s+', ' ', x)
        if '+' in x:
            segments = [s.strip().replace(' ', '_') for s in x.split('+')]
            return '+'.join(segments)
        return x.replace(' ', '_')

    # Normalize 'Variable' and 'Related_Variables' columns
    for col in ['Variable', 'Related_Variables']:
        if col in df.columns:
            df[col] = df[col].astype(str).map(normalize_string)

    # Convert 1-based Excel indices to 0-based Python indices
    index_cols = ['column_index', 'column_index_from']
    for col in index_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
            # Subtract 1 only where values are not NaN
            df[col] = df[col].apply(lambda x: x - 1 if pd.notnull(x) else x)

    # Attempt to convert all columns to numeric where possible
    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col])
        except (ValueError, TypeError):
            continue

    return df


def rename_columns_by_index(df: pd.DataFrame, demographic_dict: List[Dict[str, Any]]) -> Tuple[pd.DataFrame, List[str]]:
    """Renames DataFrame columns based on provided index-to-variable mappings.

    Args:
        df: The DataFrame to rename.
        demographic_dict: List of dictionaries containing 'column_index' and 'Variable'.

    Returns:
        Tuple[pd.DataFrame, List[str]]: The renamed DataFrame and a list of new column names.
    """
    df = df.copy()
    new_names = []
    for entry in demographic_dict:
        idx = entry.get('column_index')
        new_name = entry.get('Variable')
        if idx is not None and 0 <= int(idx) < len(df.columns):
            old_name = df.columns[int(idx)]
            df.rename(columns={old_name: new_name}, inplace=True)
            new_names.append(new_name)
    return df, new_names


def rename_variable_columns(df: pd.DataFrame, variable_dict: List[Dict[str, Any]]) -> Tuple[pd.DataFrame, List[str]]:
    """Renames variable columns based on start index and number of questions.

    Args:
        df: Input DataFrame.
        variable_dict: List of dicts with 'Variable', 'column_index_from', and 'number_questions'.

    Returns:
        Tuple[pd.DataFrame, List[str]]: Renamed DataFrame and list of all renamed columns.
    """
    df = df.copy()
    all_new_names = []
    for entry in variable_dict:
        var_name = entry.get('Variable')
        start_idx = entry.get('column_index_from')
        count = entry.get('number_questions')

        try:
            start_idx = int(float(start_idx))
            count = int(float(count))
        except (ValueError, TypeError):
            continue

        for i in range(start_idx, start_idx + count):
            if i < len(df.columns):
                old_name = df.columns[i]
                new_name = f"{var_name}_Q{i - start_idx + 1}"
                df.rename(columns={old_name: new_name}, inplace=True)
                all_new_names.append(new_name)
            
    return df, all_new_names



